ci: added canary workflow

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,164 @@
 version: 2.1
 
+orbs:
+  # Using inline orb for now
+  getting-started-smoke-test:
+    orbs:
+      macos: circleci/macos@2
+      android: circleci/android@2.0.3
+      flutter-orb: circleci/flutter@1.0.1
+
+    executors:
+      mac-executor:
+        macos:
+          xcode: 13.3.1
+        resource_class: large
+
+      android-executor:
+        machine:
+          image: android:202102-01
+        resource_class: large
+
+    commands:
+      run-with-retry:
+        description: Run command with retry
+        parameters:
+          label:
+            description: Display name
+            type: string
+          command:
+            description: Command to run
+            type: string
+          retry-count:
+            description: Number of retry
+            type: integer
+            default: 3
+          sleep:
+            description: Wait duration until next retry
+            type: integer
+            default: 5
+          no_output_timeout:
+            description: Elapsed time the command can run without output
+            type: string
+            default: 10m
+        steps:
+          - run:
+              name: << parameters.label >>
+              command: |
+                retry() {
+                  MAX_RETRY=<< parameters.retry-count >>
+                  n=0
+                  until [ $n -ge $MAX_RETRY ]
+                  do
+                      << parameters.command >> && break
+                      n=$[$n+1]
+                      sleep << parameters.sleep >>
+                  done
+                  if [ $n -ge $MAX_RETRY ]; then
+                    echo "failed: ${@}" >&2
+                    exit 1
+                  fi
+                }
+                retry
+              no_output_timeout: << parameters.no_output_timeout >>
+      install-flutter:
+        description: Install Flutter and set up paths.
+        parameters:
+          flutter_branch:
+            description: Flutter branch or version tag.
+            type: string
+            default: stable
+        steps:
+          - run:
+              name: Set up Flutter
+              command: |
+                echo 'export FLUTTER_HOME=${HOME}/sdks/flutter' >> $BASH_ENV
+                echo 'export FLUTTER_BRANCH=<< parameters.flutter_branch >>' >> $BASH_ENV
+                echo 'export FLUTTER_ROOT=${FLUTTER_HOME}' >> $BASH_ENV
+                echo 'export PATH=${PATH}:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin:${HOME}/.pub-cache/bin:${FLUTTER_HOME}/.pub-cache/bin' >> $BASH_ENV
+                source $BASH_ENV
+                git clone --branch ${FLUTTER_BRANCH} https://github.com/flutter/flutter.git ${FLUTTER_HOME}
+                (yes || true) | flutter doctor --android-licenses && flutter doctor
+                flutter precache
+      setup-amplify-flutter-project:
+        description: Setup Amplify project
+        steps:
+          - run-with-retry:
+              label: Setting up dependences
+              command: cd amplified_todo && flutter pub add amplify_flutter && flutter pub add amplify_datastore
+              no_output_timeout: 20m
+          - run:
+              name: Adding integration_test package
+              command: 'cd amplified_todo && sed -i -e "s/dev_dependencies:/dev_dependencies:\n  integration_test:\n    sdk: flutter/" ./pubspec.yaml && cat ./pubspec.yaml'
+          - run:
+              name: Update outdated dependences
+              command: cd amplified_todo && flutter pub upgrade --major-versions
+          - run:
+              name: Adding Amplify code
+              command: mv canaries/dummy_amplifyconfiguration.dart canaries/amplifyconfiguration.dart && cp canaries/amplifyconfiguration.dart amplified_todo/lib && cp canaries/main.dart amplified_todo/lib && cp -r canaries/integration_test amplified_todo/integration_test
+
+
+    jobs:
+      flutter-android:
+        executor:
+          name: android/android-machine
+          resource-class: large
+          tag: 2021.10.1
+        steps:
+          - checkout
+          - install-flutter
+          - run:
+              name: Setting up project
+              command: flutter create amplified_todo
+          - run:
+              name: Update Android version
+              command: cd amplified_todo && sed -i -e "s/minSdkVersion .*/minSdkVersion 21/" ./android/app/build.gradle && cat ./android/app/build.gradle
+          - setup-amplify-flutter-project
+          - flutter-orb/install_android_gradle:
+              app-dir: ./amplified_todo
+          - android/create-avd:
+              avd-name: flutter
+              install: true
+              system-image: system-images;android-29;default;x86
+          - android/start-emulator:
+              avd-name: flutter
+              post-emulator-launch-assemble-command: ls -lrt
+              restore-gradle-cache-find-args: ./amplified_todo/android -name 'build.gradle'
+          - run-with-retry:
+              label: Run Flutter Build
+              command: cd amplified_todo && flutter build apk --debug -v
+              no_output_timeout: 20m
+          - run-with-retry:
+              label: Run Flutter Tests
+              command: cd amplified_todo && flutter test integration_test -v
+              no_output_timeout: 1h
+              retry-count: 5
+
+      flutter-ios:
+        executor: mac-executor
+        steps:
+          - checkout
+          - macos/preboot-simulator:
+              device: iPhone 13
+              version: "15.4"
+          - install-flutter
+          - run:
+              name: Setting up project
+              command: flutter create amplified_todo
+          - setup-amplify-flutter-project
+          - run:
+              name: Update ios version
+              command: cd amplified_todo && sed -i -e "s/# platform :ios, '9.0'/platform :ios, '13.0'/" ./ios/Podfile
+          - run-with-retry:
+              label: Run Flutter Build
+              command: cd amplified_todo && flutter build ios --debug -v --simulator
+              no_output_timeout: 20m
+          - run-with-retry:
+              label: Run Flutter Tests
+              command: cd amplified_todo && flutter test integration_test -v
+              no_output_timeout: 20m
+
+
 executors:
   docker-executor:
     docker:
@@ -50,6 +209,7 @@ commands:
           name: Install tuneup
           command: |
             flutter pub global activate tuneup
+
 jobs:
   format_flutter:
     executor: docker-executor
@@ -197,7 +357,13 @@ releasable_branches: &releasable_branches
       - main
 
 workflows:
+  # Tells CircleCI to skip this workflow when the pipeline is triggered by the scheduled source,
+  # i.e. when the canaries workflow executes
+  # https://circleci.com/docs/2.0/scheduled-pipelines/#workflows-filtering
   test_deploy:
+    when:
+      not:
+        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
     jobs:
       - format_flutter
       - analyze_flutter
@@ -254,3 +420,13 @@ workflows:
                   "amplify_datastore",
                   "amplify_flutter",
                 ]
+  # Scheduled smoke test workflow
+  # Jobs are pulled from the getting-started-smoke-test inline orb defined below
+  canaries:
+#    when:
+#      and:
+#        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
+#        - equal: [ "Canaries", << pipeline.schedule.name >> ]
+    jobs:
+      - getting-started-smoke-test/flutter-android
+      - getting-started-smoke-test/flutter-ios
